version: 0.2

phases:
  install:
    commands:
      - echo "Installing backend dependencies..."
      - cd api
      - npm install --production
  build:
    commands:
      - echo "Preparing backend deployment package..."
      - cd ..
      # Move contents of api/ (not the folder itself) into bundle/
      - mkdir -p bundle
      - cp -r api/* bundle/
      - cp -r api/.* bundle/ || true
      # Procfile (important for Elastic Beanstalk Node.js platform)
      - echo "web: node app.js" > bundle/Procfile
      - cd bundle
      - zip -r ../backend.zip .
artifacts:
  files:
    - backend.zip
