version: 0.2

phases:
  install:
    commands:
      - echo "Installing frontend dependencies..."
      - cd client
      - npm install
  build:
    commands:
      - echo "Building React app..."
      - npm run build
      - cd ..
      - echo "Preparing Dockerized frontend package..."
      - mkdir -p bundle
      # Copy Dockerfile and configs
      - cp Dockerfile bundle/
      - cp default.conf bundle/
      - cp env.sh bundle/
      # Copy built React files
      - cp -r client/build bundle/build
      - cd bundle
      - zip -r ../frontend.zip .
artifacts:
  files:
    - frontend.zip
